"""revamped_stocks

Revision ID: 8471e5ba2130
Revises: 192f8a1ac46a
Create Date: 2026-03-23 18:09:56.434984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8471e5ba2130'
down_revision: Union[str, None] = '192f8a1ac46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
